url: datafoodconsortium.github.io
baseurl:

# Site settings
title: Data Food Consortium
email: info@datafoodconsortium
description: "Développons des standards ouverts de données pour les acteurs du système alimentaire"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url:
  - title: github
    url: http://github.com/

collections:
 membres:
  title: membres
  output: false

# Build settings
markdown: kramdown
permalink: pretty