url: http://datafoodconsortium.org/
baseurl:

# Site settings
title: Data Food Consortium
email: info@datafoodconsortium
description: "Développons des standards ouverts de données pour les acteurs du système alimentaire"
description_en: "Developing open data standards for the food system"
twitter_username: "dfconsortium"


# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: facebook
    url: https://www.facebook.com/datafoodconsortium/
  - title: github
    url: https://github.com/datafoodconsortium
  - title: twitter
    url: https://twitter.com/dfconsortium

collections:
 membres:
  title: membres
  output: false
 redacteurs:
  title: redacteurs
  output: true

t:
 fr:
  enjeux:
   name: "Enjeux"
   url: "#enjeux"
  objectifs:
   name: "Objectifs"
   url: "#objectifs"
  team:
   name: "Membres"
   url: "#team"
  contact:
   name: "Contact"
   url: "#contact"
 en:
  challenges:
   name: "Issues"
   url: "#challenges"
  objectives:
   name: "Goals"
   url: "#goals"
  members:
   name: "Members"
   url: "#team"
  contact:
   name: "Contact"
   url: "#contact"
foot:
  fr:
   enjeux:
    name: "Enjeux"
    url: "#enjeux"
   objectifs:
    name: "Objectifs"
    url: "#objectifs"
   team:
    name: "Membres"
    url: "#team"
   contact:
    name: "Contact"
    url: "#contact"
  en:
   challenges:
    name: "Issues"
    url: "#challenges"
   objectives:
    name: "Goals"
    url: "#goals"
   members:
    name: "Members"
    url: "#team"
   contact:
    name: "Contact"
    url: "#contact"

defaults:
- scope:
    path: ''
    type: posts
  values:
    lang: 'en'
    layout: post
    title: ''
    description: ''
    auteur: ''
    img: ''
    comments: ''
- scope:
    path: ''
    type: redacteurs
  values:
    lang: 'en'
    layout: auteur
    avatar: ''
    twitter: ''
    description: ''
- scope:
    path: ''
    type: membres
  values:
    nom: ''
    img: ''
    website: ''

# Build settings
markdown: kramdown
permalink: "/blog/:title"
