---
new_page_extension: md
auto_deploy: false
admin_path: "/admin"
webhook_url: 
collections: 
upload_dir: img
public_path: "/img"
front_matter_path: img
use_front_matter_path: true
file_template: ":filename:"
